#!/usr/bin/env python3

import sys
import re
import subprocess

if len(sys.argv) < 2 or len(sys.argv) > 3:
    print("Usage: downgit <git_folder_url> [<local_folder>]")
    sys.exit(1)

git_url = sys.argv[1]
if ("/tree/" in git_url):
    svn_url = re.sub(r"^https:\/\/github.com\/([^\/]+)\/([^\/]+)\/tree\/[^\/]+\/(.+)$", r"https://github.com/\1/\2/trunk/\3", git_url)
else:
    svn_url = re.sub(r"^https:\/\/github.com\/([^\/]+)\/([^\/]+)\/(.+)$", r"https://github.com/\1/\2/trunk/\3", git_url)


if len(sys.argv) == 3:
    local_folder = sys.argv[2]
    svn_cmd = ["svn", "export", svn_url, local_folder]
else:
    svn_cmd = ["svn", "export", svn_url]

print(f"Downloading {svn_url} ...")
try:
    subprocess.run(svn_cmd, check=True)
except subprocess.CalledProcessError:
    print(f"Error: Could not download {svn_url}")
    sys.exit(1)

print(f"Downloaded {svn_url} to {local_folder if len(sys.argv) == 3 else '.'}")
