#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo -e "\e[31mPlease run as root\e[0m"
  exit
fi

chmod +x ./downgit
sudo apt install -y subversion
cp ./downgit /usr/bin/

echo -e "\e[32mdowngit installed successfully in \e[34m/usr/bin/\e[0m"
echo ""
echo -e "If you like this tool, please star the repo at \e[34mhttps://github.com/ZKAW/downgit\e[0m \e[32m:) \e[0m"
